import { makeStyles } from "@rneui/themed";
import { FONTS } from "./fonts";

export const sharedTextStyles = makeStyles((theme) => ({
  blackSmallLight: {
    fontSize: 12,
    letterSpacing: 0.1,
    fontWeight: 400,
    color: theme.colors.black,
  },
  blackSmallRegular: {
    fontSize: 12,
    letterSpacing: 0.1,
    fontWeight: 500,
    color: theme.colors.black,
  },
  blackSmallSemiBold: {
    fontSize: 12,
    letterSpacing: 0.1,
    fontWeight: 600,
    color: theme.colors.black,
  },
  blackSmallBold: {
    fontSize: 12,
    letterSpacing: 0.1,
    fontWeight: 700,
    color: theme.colors.black,
  },
  blackSmallExtra: {
    fontSize: 12,
    letterSpacing: 0.1,
    fontWeight: 800,
    color: theme.colors.black,
  },
  blackMediumLight: {
    fontSize: 14,
    letterSpacing: 0.1,
    fontWeight: 400,
    color: theme.colors.black,
  },
  blackMediumRegular: {
    fontSize: 14,
    letterSpacing: 0.1,
    fontWeight: 500,
    color: theme.colors.black,
  },
  blackMediumSemiBold: {
    fontSize: 14,
    letterSpacing: 0.1,
    fontWeight: 600,
    color: theme.colors.black,
  },
  blackMediumBold: {
    fontSize: 14,
    letterSpacing: 0.1,
    color: theme.colors.black,
    fontWeight: 700,
  },
  blackMediumExtra: {
    fontSize: 14,
    letterSpacing: 0.1,
    fontWeight: 800,
    color: theme.colors.black,
  },
  blackBigLight: {
    fontSize: 18,
    letterSpacing: 0.1,
    fontWeight: 400,
    color: theme.colors.black,
  },
  blackBigRegular: {
    fontSize: 18,
    letterSpacing: 0.1,
    fontWeight: 500,
    color: theme.colors.black,
  },
  blackBigBold: {
    fontSize: 18,
    letterSpacing: 0.1,
    fontWeight: 700,
    color: theme.colors.black,
  },
  blackBigExtra: {
    fontSize: 18,
    letterSpacing: 0.1,
    fontWeight: 800,
    color: theme.colors.black,
  },
  primarySmallLight: {
    fontSize: 12,
    letterSpacing: 0.1,
    fontWeight: 400,
    color: theme.colors.primary,
  },
  primarySmallRegular: {
    fontSize: 12,
    letterSpacing: 0.1,
    fontWeight: 500,
    color: theme.colors.primary,
  },
  primarySmallBold: {
    fontSize: 12,
    letterSpacing: 0.1,
    fontWeight: 700,
    color: theme.colors.primary,
  },
  primarySmallExtra: {
    fontSize: 12,
    letterSpacing: 0.1,
    fontWeight: 800,
    color: theme.colors.primary,
  },
  primaryMediumLight: {
    fontSize: 14,
    letterSpacing: 0.1,
    fontWeight: 400,
    color: theme.colors.primary,
  },
  primaryMediumRegular: {
    fontSize: 14,
    letterSpacing: 0.1,
    fontWeight: 500,
    color: theme.colors.primary,
  },
  primaryMediumBold: {
    fontSize: 14,
    letterSpacing: 0.1,
    fontWeight: 700,
    color: theme.colors.primary,
  },
  primaryMediumExtra: {
    fontSize: 14,
    letterSpacing: 0.1,
    fontWeight: 800,
    color: theme.colors.primary,
  },
  primaryBigLight: {
    fontSize: 18,
    letterSpacing: 0.1,
    fontWeight: 400,
    color: theme.colors.primary,
  },
  primaryBigRegular: {
    fontSize: 18,
    letterSpacing: 0.1,
    fontWeight: 500,
    color: theme.colors.primary,
  },
  primaryBigBold: {
    fontSize: 18,
    letterSpacing: 0.1,
    fontWeight: 700,
    color: theme.colors.primary,
  },
  primaryBigExtra: {
    fontSize: 18,
    letterSpacing: 0.1,
    fontWeight: 800,
    color: theme.colors.primary,
  },
  secondarySmallLight: {
    fontSize: 12,
    letterSpacing: 0.1,
    fontWeight: 400,
    color: theme.colors.secondary_text,
  },
  secondarySmallRegular: {
    fontSize: 12,
    letterSpacing: 0.1,
    fontWeight: 500,
    color: theme.colors.secondary_text,
  },
  secondarySmallBold: {
    fontSize: 12,
    letterSpacing: 0.1,
    fontWeight: 700,
    color: theme.colors.secondary_text,
  },
  secondarySmallExtra: {
    fontSize: 12,
    letterSpacing: 0.1,
    fontWeight: 800,
    color: theme.colors.secondary_text,
  },
  secondaryMediumLight: {
    fontSize: 14,
    letterSpacing: 0.1,
    fontWeight: 400,
    color: theme.colors.secondary_text,
  },
  secondaryMediumRegular: {
    fontSize: 14,
    letterSpacing: 0.1,
    fontWeight: 500,
    color: theme.colors.secondary_text,
  },
  secondaryMediumBold: {
    fontSize: 14,
    letterSpacing: 0.1,
    fontWeight: 700,
    color: theme.colors.secondary_text,
  },
  secondaryMediumExtra: {
    fontSize: 14,
    letterSpacing: 0.1,
    fontWeight: 800,
    color: theme.colors.secondary_text,
  },
  secondaryBigLight: {
    fontSize: 18,
    letterSpacing: 0.1,
    fontWeight: 400,
    color: theme.colors.secondary_text,
  },
  secondaryBigRegular: {
    fontSize: 18,
    letterSpacing: 0.1,
    fontWeight: 500,
    color: theme.colors.secondary_text,
  },
  secondaryBigBold: {
    fontSize: 18,
    letterSpacing: 0.1,
    fontWeight: 700,
    color: theme.colors.secondary_text,
  },
  secondaryBigExtra: {
    fontSize: 18,
    letterSpacing: 0.1,
    fontWeight: 800,
    color: theme.colors.secondary_text,
  },
  whiteSmallLight: {
    fontSize: 12,
    letterSpacing: 0.1,
    fontWeight: 400,
    color: theme.colors.white,
  },
  whiteSmallRegular: {
    fontSize: 12,
    letterSpacing: 0.1,
    fontWeight: 500,
    color: theme.colors.white,
  },
  whiteSmallSemiBold: {
    fontSize: 12,
    letterSpacing: 0.1,
    fontWeight: 600,
    color: theme.colors.white,
  },
  whiteSmallBold: {
    fontSize: 12,
    letterSpacing: 0.1,
    fontWeight: 700,
    color: theme.colors.white,
  },
  whiteSmallExtra: {
    fontSize: 12,
    letterSpacing: 0.1,
    fontWeight: 800,
    color: theme.colors.white,
  },
  whiteMediumLight: {
    fontSize: 14,
    letterSpacing: 0.1,
    fontWeight: 400,
    color: theme.colors.white,
  },
  whiteMediumRegular: {
    fontSize: 14,
    letterSpacing: 0.1,
    fontWeight: 500,
    color: theme.colors.white,
  },
  whiteMediumSemiBold: {
    fontSize: 14,
    letterSpacing: 0.1,
    fontWeight: 600,
    color: theme.colors.white,
  },
  whiteMediumBold: {
    fontSize: 14,
    letterSpacing: 0.1,
    fontWeight: 700,
    color: theme.colors.white,
  },
  whiteMediumExtra: {
    fontSize: 14,
    letterSpacing: 0.1,
    fontWeight: 800,
    color: theme.colors.white,
  },
  whiteBigLight: {
    fontSize: 18,
    letterSpacing: 0.1,
    fontWeight: 400,
    color: theme.colors.white,
  },
  whiteBigRegular: {
    fontSize: 18,
    letterSpacing: 0.1,
    fontWeight: 500,
    color: theme.colors.white,
  },
  whiteBigBold: {
    fontSize: 18,
    letterSpacing: 0.1,
    fontWeight: 700,
    color: theme.colors.white,
  },
  whiteBigExtra: {
    fontSize: 18,
    letterSpacing: 0.1,
    fontWeight: 800,
    color: theme.colors.white,
  },
}));
